"""Joinery templates — Phase 2, brief Part 3.

Part sizes are a function of ``(dimensions, allowances, joinery_template)`` — never
of dimensions alone. A template also carries a *fastener schedule* and *implied
operations*; the tool schedule is **derived from the operation list**, not
authored (Part 3). If a tool appears without an operation that requires it, that
is a bug.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable

from ..catalog.fasteners import get_fastener


@dataclass(frozen=True)
class Joint:
    """One fastened seam. Fastener count is derived from length and spacing."""

    name: str
    fastener_id: str
    seam_length: float        # linear inches of the seam
    spacing: float            # inches between fasteners
    rows: int = 1             # parallel rows of fasteners
    operation: str = ""       # the operation that implies tools

    def count(self) -> int:
        per_row = max(2, int(self.seam_length // self.spacing) + 1)
        return per_row * self.rows


@dataclass(frozen=True)
class ToolEntry:
    tool: str
    setting: str
    justified_by: str         # the operation that requires it — never empty


@dataclass(frozen=True)
class JoineryTemplate:
    id: str
    applies_to: tuple[str, ...]
    is_default: bool
    description: str


# Operation -> tool mapping. The tool schedule is generated by walking the
# operations actually present in the joint/skin lists (Part 3).
_OPERATION_TOOLS: dict[str, list[ToolEntry]] = {
    "rip_sheet_goods": [
        ToolEntry("table saw", "80T crosscut / rip blade, zero-clearance insert", "rip_sheet_goods"),
    ],
    "crosscut_panels": [
        ToolEntry("track saw", "guide rail, 48in", "crosscut_panels"),
    ],
    "drill_pilot_countersink": [
        ToolEntry("drill/driver", "7/64 brad-point pilot + countersink", "drill_pilot_countersink"),
    ],
    "drive_cabinet_screw": [
        ToolEntry("impact driver", "#2 square bit", "drive_cabinet_screw"),
    ],
    "pocket_screw": [
        ToolEntry("pocket-hole jig", "set to 3/4 stock thickness", "pocket_screw"),
        ToolEntry("drill/driver", "3/8 stepped pocket bit", "pocket_screw"),
    ],
    "brad_nail": [
        ToolEntry("18ga brad nailer", "1in brads, 70psi", "brad_nail"),
    ],
    "cut_cement_board": [
        ToolEntry("carbide scoring knife", "straightedge, score-and-snap", "cut_cement_board"),
        ToolEntry("P100 respirator", "mandatory — silica dust", "cut_cement_board"),
        ToolEntry("angle grinder", "diamond blade, for cutouts only", "cut_cement_board"),
    ],
    "drive_cement_board_screw": [
        ToolEntry("drill/driver", "#2 Phillips, clutch set low", "drive_cement_board_screw"),
    ],
    "trowel_microcement": [
        ToolEntry("stainless trowel", "flexible, 4in and 11in", "trowel_microcement"),
        ToolEntry("orbital sander", "220/400 grit between coats", "trowel_microcement"),
    ],
}


def tool_schedule(operations: set[str]) -> tuple[ToolEntry, ...]:
    """Derive the tool schedule from the set of operations present.

    Never authored directly. Every entry traces to an operation in ``operations``.
    """
    out: list[ToolEntry] = []
    seen: set[tuple[str, str]] = set()
    for op in sorted(operations):
        if op not in _OPERATION_TOOLS:
            raise KeyError(f"operation {op!r} has no tool mapping (Part 3: no unjustified tools)")
        for te in _OPERATION_TOOLS[op]:
            key = (te.tool, te.setting)
            if key not in seen:
                seen.add(key)
                out.append(te)
    return tuple(out)


def fastener_bom(joints: tuple[Joint, ...]) -> dict[str, dict]:
    """Aggregate a derived fastener bill by fastener id."""
    bom: dict[str, dict] = {}
    for j in joints:
        f = get_fastener(j.fastener_id)
        rec = bom.setdefault(
            j.fastener_id,
            {"fastener": f, "count": 0, "pilot": f.pilot_diameter,
             "countersink": f.countersink_diameter, "driver": f.driver_bit},
        )
        rec["count"] += j.count()
    return bom
